server:
  port: 9090
  error:
    include-message: always
    include-binding-errors: always
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/recipe-vault
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:140108}
    driverClassname: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/recipevault
app:
  name: recipevault
  keycloak:
    client-name: recipevault